### ISSUE TITLE
Why are the timestamps of these events out of order？

### ISSUE THREAD

**Issue by username123062** [Lynn0306/DVS-Voltmeter#5]
Hi, Thanks for sharing your code. I am very confused that when I print out the events generated by the event_generator, the timestamps of these events for a video are disordered, which is a big difference between your work and the method "V2E" mentioned in your paper. 

And the generated event video is totally wrong if we sort these events . So could you help to explain it? Thanks a lot.
==============================================
============== disordered events===================
6.556896183569176e-05 96 7 0
6.516170384144115e-05 95 8 0
5.759480559259039e-05 93 9 0
6.409560533079641e-05 94 9 0
6.108955837193494e-05 95 9 0
5.228459463260592e-05 93 10 0
5.526730238358448e-05 94 10 0
5.8839238849654394e-05 95 10 0
5.649529605214436e-05 92 11 0
4.911262847482427e-05 93 11 0
4.957900805844507e-05 94 11 0
5.7014078401869496e-05 95 11 0
5.733279457837989e-05 91 12 0
5.13671718597383e-05 92 12 0
4.8674903479624226e-05 93 12 0
4.911898590369475e-05 94 12 0
5.9105478502334494e-05 95 12 0
5.448996675445537e-05 91 13 0
5.110803543773683e-05 92 13 0
5.4467109848753275e-05 93 13 0
5.227742510433856e-05 94 13 0
5.8719752315650326e-05 91 14 0
5.75497173930737e-05 92 14 0
5.399478779905652e-05 95 15 1

**Comment by OliveMY** [comment]
Thank you for your feedback. In our method, the timestamps of events are sampled asynchronously between pixels, causing the disorder. We did sort events in the experiments included in our paper. Could you please clarify how you create the videos?

**Comment by OliveMY** [comment]
In addition, I noticed that the timestamps you recorded are float, which should be integers in the code. Could you please share the code recording the events and generating the videos?
